title = "Stew"  # From Git
gitRepoUrl = "https://github.com/SolarScuffle-Bot/Stew/" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

# From git:
organizationName = "Sona"
projectName = "Stew"
url = "https://SolarScuffle-Bot.github.io"
baseUrl = "/Stew/"
tagline = "Brewing the next generation"

# [navbar]
# hideableSidebar = true

[footer]
style = "dark"
copyright = "Copyright © 2021 SolarScuffle-Bot. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"