[package]
name = "solarscuffle-bot/stew"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["Sona <synapsescuffle@gmail.com>"]

realm = "shared"

exclude = ["README.md"]

[dependencies]
