[package]
name = "data-oriented-house/rbxstew"
version = "0.3.1"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["Sona"]

description = "RBXStew is the Roblox-specific successor to Stew, a very small and lightweight Entity-Component module used for creating and composing entity tables with components. Similar to the ECS pattern, but allowing the user to define their own systems under the philosophy it is user logic. It offers a concise API for constructing components, creating entities and components, and getting intersections of all entities with certain components."

realm = "shared"

exclude = ["README.md"]

[dependencies]